/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment5;

import main.java.assignment5.AsyncThreadingDemo;

public class App {

   public static void main(String[] args) {
        int n = 5; 

        System.out.println("=== 1) Runnable + Lambda + Thread + join ===");
        AsyncThreadingDemo.runWithThreadLambda(n);

        System.out.println("\n=== 2) Runnable + ExecutorService ===");
        AsyncThreadingDemo.runWithExecutorService(n);

        System.out.println("\n=== 3) CompletableFuture: runAsync + supplyAsync ===");
        AsyncThreadingDemo.runWithCompletableFuture(n);

        System.out.println("\nDone.");
    }
}
