/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.time.Duration;

public class AppTest {
    @Test
    public void runsScenario1_threadRunnableLambda() {
        assertTimeoutPreemptively(Duration.ofSeconds(3), () -> {
            AsyncThreadingDemo.runWithThreadLambda(2);
        });
    }

    @Test
    public void runsScenario2_executorService() {
        assertTimeoutPreemptively(Duration.ofSeconds(5), () -> {
            AsyncThreadingDemo.runWithExecutorService(2);
        });
    }

    @Test
    public void runsScenario3_completableFuture() {
        assertTimeoutPreemptively(Duration.ofSeconds(5), () -> {
            AsyncThreadingDemo.runWithCompletableFuture(2);
        });
    }
}
