/*
 * This source file was generated by the Gradle 'init' task
 */
package threads;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testThreads01() {
        ThreadExamples.threads01(10);
    }   

    @Test void testThreads00() {
        ThreadExamples.threads00(8);
    }
}
